# basic configuration
baseurl: /course-in-a-box
markdown: redcarpet
permalink: /:categories/:title/

# Change this tracking code with your own tracking code
ga_tracking_code: UA-5757664-19
# Please leave this code here for us to see how Course in a Box get used
p2pu_ga_tracking_code: UA-55722824-1

# Some files we need to exclude, so Github can build the site
exclude: [Gemfile, Gemfile.lock, README.md]

defaults:
  -
    scope:
      path: "modules" # an empty string here means all files in the project
    values:
      layout: "course_page"

prose:
  media: img
  ignore:
    - /_includes
    - /_layouts
    - /_sass
    - /fonts
    - /js
    - /css

# Set some personal styles and logo for your course
# this is a hex value http://www.w3schools.com/tags/ref_colorpicker.asp
jumbotron_color: " #FF0000"
jumbotron_background_image: "https://cloud.githubusercontent.com/assets/10998057/9138018/1eae654a-3ce7-11e5-8c91-826f08a1d2e7.jpg"
jumbotron_image: "box-icon.png"
